// List of 100+ popular NSE (National Stock Exchange) Indian stocks
// Format: { name: "Company Name", ticker: "TICKER.NS" }

export const indianStocks = [
  // NIFTY 50 Components
  { name: "Reliance Industries", ticker: "RELIANCE.NS" },
  { name: "Tata Consultancy Services", ticker: "TCS.NS" },
  { name: "HDFC Bank", ticker: "HDFCBANK.NS" },
  { name: "Infosys", ticker: "INFY.NS" },
  { name: "ICICI Bank", ticker: "ICICIBANK.NS" },
  { name: "Hindustan Unilever", ticker: "HINDUNILVR.NS" },
  { name: "State Bank of India", ticker: "SBIN.NS" },
  { name: "Bharti Airtel", ticker: "BHARTIARTL.NS" },
  { name: "ITC Limited", ticker: "ITC.NS" },
  { name: "Kotak Mahindra Bank", ticker: "KOTAKBANK.NS" },
  { name: "Larsen & Toubro", ticker: "LT.NS" },
  { name: "Axis Bank", ticker: "AXISBANK.NS" },
  { name: "Asian Paints", ticker: "ASIANPAINT.NS" },
  { name: "Maruti Suzuki", ticker: "MARUTI.NS" },
  { name: "Bajaj Finance", ticker: "BAJFINANCE.NS" },
  { name: "HCL Technologies", ticker: "HCLTECH.NS" },
  { name: "Titan Company", ticker: "TITAN.NS" },
  { name: "Sun Pharmaceutical", ticker: "SUNPHARMA.NS" },
  { name: "Wipro", ticker: "WIPRO.NS" },
  { name: "Tata Motors", ticker: "TATAMOTORS.NS" },
  { name: "UltraTech Cement", ticker: "ULTRACEMCO.NS" },
  { name: "Nestle India", ticker: "NESTLEIND.NS" },
  { name: "Power Grid Corporation", ticker: "POWERGRID.NS" },
  { name: "NTPC Limited", ticker: "NTPC.NS" },
  { name: "Mahindra & Mahindra", ticker: "M&M.NS" },
  { name: "Tech Mahindra", ticker: "TECHM.NS" },
  { name: "Bajaj Finserv", ticker: "BAJAJFINSV.NS" },
  { name: "IndusInd Bank", ticker: "INDUSINDBK.NS" },
  { name: "Tata Steel", ticker: "TATASTEEL.NS" },
  { name: "Adani Enterprises", ticker: "ADANIENT.NS" },
  { name: "JSW Steel", ticker: "JSWSTEEL.NS" },
  { name: "Grasim Industries", ticker: "GRASIM.NS" },
  { name: "Dr. Reddy's Laboratories", ticker: "DRREDDY.NS" },
  { name: "Coal India", ticker: "COALINDIA.NS" },
  { name: "Cipla", ticker: "CIPLA.NS" },
  { name: "Britannia Industries", ticker: "BRITANNIA.NS" },
  { name: "Eicher Motors", ticker: "EICHERMOT.NS" },
  { name: "ONGC", ticker: "ONGC.NS" },
  { name: "Hindalco Industries", ticker: "HINDALCO.NS" },
  { name: "Hero MotoCorp", ticker: "HEROMOTOCO.NS" },
  { name: "Divi's Laboratories", ticker: "DIVISLAB.NS" },
  { name: "Apollo Hospitals", ticker: "APOLLOHOSP.NS" },
  { name: "Bajaj Auto", ticker: "BAJAJ-AUTO.NS" },
  { name: "SBI Life Insurance", ticker: "SBILIFE.NS" },
  { name: "HDFC Life Insurance", ticker: "HDFCLIFE.NS" },
  { name: "Adani Ports", ticker: "ADANIPORTS.NS" },
  { name: "Tata Consumer Products", ticker: "TATACONSUM.NS" },
  { name: "BPCL", ticker: "BPCL.NS" },
  { name: "Shree Cement", ticker: "SHREECEM.NS" },
  { name: "Bharat Electronics", ticker: "BEL.NS" },
  
  // NIFTY Next 50 & Popular Mid-caps
  { name: "Avenue Supermarts (DMart)", ticker: "DMART.NS" },
  { name: "Vedanta Limited", ticker: "VEDL.NS" },
  { name: "Godrej Consumer Products", ticker: "GODREJCP.NS" },
  { name: "ICICI Lombard", ticker: "ICICIGI.NS" },
  { name: "ICICI Prudential Life", ticker: "ICICIPRULI.NS" },
  { name: "Pidilite Industries", ticker: "PIDILITIND.NS" },
  { name: "Havells India", ticker: "HAVELLS.NS" },
  { name: "Siemens India", ticker: "SIEMENS.NS" },
  { name: "Ambuja Cements", ticker: "AMBUJACEM.NS" },
  { name: "ACC Limited", ticker: "ACC.NS" },
  { name: "DLF Limited", ticker: "DLF.NS" },
  { name: "Info Edge (Naukri)", ticker: "NAUKRI.NS" },
  { name: "Marico Limited", ticker: "MARICO.NS" },
  { name: "Bandhan Bank", ticker: "BANDHANBNK.NS" },
  { name: "Zomato", ticker: "ZOMATO.NS" },
  { name: "Paytm (One97)", ticker: "PAYTM.NS" },
  { name: "PB Fintech (Policybazaar)", ticker: "POLICYBZR.NS" },
  { name: "Nykaa (FSN E-Commerce)", ticker: "NYKAA.NS" },
  { name: "Adani Green Energy", ticker: "ADANIGREEN.NS" },
  { name: "Adani Total Gas", ticker: "ATGL.NS" },
  { name: "Adani Power", ticker: "ADANIPOWER.NS" },
  { name: "Adani Wilmar", ticker: "AWL.NS" },
  { name: "Torrent Pharma", ticker: "TORNTPHARM.NS" },
  { name: "Lupin", ticker: "LUPIN.NS" },
  { name: "Aurobindo Pharma", ticker: "AUROPHARMA.NS" },
  { name: "Biocon", ticker: "BIOCON.NS" },
  { name: "Jubilant FoodWorks", ticker: "JUBLFOOD.NS" },
  { name: "Page Industries", ticker: "PAGEIND.NS" },
  { name: "Muthoot Finance", ticker: "MUTHOOTFIN.NS" },
  { name: "Cholamandalam Investment", ticker: "CHOLAFIN.NS" },
  { name: "Shriram Finance", ticker: "SHRIRAMFIN.NS" },
  { name: "LIC Housing Finance", ticker: "LICHSGFIN.NS" },
  { name: "PNB Housing Finance", ticker: "PNBHOUSING.NS" },
  { name: "Motherson Sumi", ticker: "MOTHERSON.NS" },
  { name: "Bosch Limited", ticker: "BOSCHLTD.NS" },
  { name: "MRF Limited", ticker: "MRF.NS" },
  { name: "Berger Paints", ticker: "BERGEPAINT.NS" },
  { name: "Colgate-Palmolive India", ticker: "COLPAL.NS" },
  { name: "Dabur India", ticker: "DABUR.NS" },
  { name: "Godrej Properties", ticker: "GODREJPROP.NS" },
  { name: "Oberoi Realty", ticker: "OBEROIRLTY.NS" },
  { name: "Phoenix Mills", ticker: "PHOENIXLTD.NS" },
  { name: "Indian Hotels (Taj)", ticker: "INDHOTEL.NS" },
  { name: "Trent Limited", ticker: "TRENT.NS" },
  { name: "Voltas", ticker: "VOLTAS.NS" },
  { name: "Crompton Greaves", ticker: "CROMPTON.NS" },
  { name: "Polycab India", ticker: "POLYCAB.NS" },
  { name: "Astral Limited", ticker: "ASTRAL.NS" },
  { name: "Supreme Industries", ticker: "SUPREMEIND.NS" },
  { name: "Dixon Technologies", ticker: "DIXON.NS" },
  { name: "Varun Beverages", ticker: "VBL.NS" },
  { name: "Tata Power", ticker: "TATAPOWER.NS" },
  { name: "Tata Elxsi", ticker: "TATAELXSI.NS" },
  { name: "L&T Technology Services", ticker: "LTTS.NS" },
  { name: "L&T Infotech (LTIMindtree)", ticker: "LTIM.NS" },
  { name: "Mphasis", ticker: "MPHASIS.NS" },
  { name: "Coforge", ticker: "COFORGE.NS" },
  { name: "Persistent Systems", ticker: "PERSISTENT.NS" },
  { name: "Indian Energy Exchange", ticker: "IEX.NS" },
  { name: "MCX India", ticker: "MCX.NS" },
  { name: "BSE Limited", ticker: "BSE.NS" },
  { name: "IRCTC", ticker: "IRCTC.NS" },
  { name: "Indian Railway Finance", ticker: "IRFC.NS" },
  { name: "HAL (Hindustan Aeronautics)", ticker: "HAL.NS" },
  { name: "Mazagon Dock", ticker: "MAZDOCK.NS" },
  { name: "Cochin Shipyard", ticker: "COCHINSHIP.NS" },
  { name: "Garden Reach Shipbuilders", ticker: "GRSE.NS" },
  { name: "Bharat Dynamics", ticker: "BDL.NS" },
  { name: "Data Patterns", ticker: "DATAPATTNS.NS" },
  { name: "Kaynes Technology", ticker: "KAYNES.NS" },
  { name: "Syrma SGS Technology", ticker: "SYRMA.NS" },
  { name: "KPIT Technologies", ticker: "KPITTECH.NS" },
  { name: "Happiest Minds", ticker: "HAPPSTMNDS.NS" },
  { name: "Zensar Technologies", ticker: "ZENSARTECH.NS" },
  { name: "CAMS", ticker: "CAMS.NS" },
  { name: "CDSL", ticker: "CDSL.NS" },
  { name: "Angel One", ticker: "ANGELONE.NS" },
  { name: "Five Star Business Finance", ticker: "FIVESTAR.NS" },
  { name: "IDFC First Bank", ticker: "IDFCFIRSTB.NS" },
  { name: "Federal Bank", ticker: "FEDERALBNK.NS" },
  { name: "RBL Bank", ticker: "RBLBANK.NS" },
  { name: "City Union Bank", ticker: "CUB.NS" },
  { name: "AU Small Finance Bank", ticker: "AUBANK.NS" },
  { name: "Equitas Small Finance", ticker: "EQUITASBNK.NS" },
  { name: "Ujjivan Small Finance", ticker: "UJJIVANSFB.NS" },
  { name: "PVR INOX", ticker: "PVRINOX.NS" },
  { name: "Zee Entertainment", ticker: "ZEEL.NS" },
  { name: "Sun TV Network", ticker: "SUNTV.NS" },
  { name: "Indigo (InterGlobe Aviation)", ticker: "INDIGO.NS" },
  { name: "SpiceJet", ticker: "SPICEJET.NS" },
  { name: "Container Corporation", ticker: "CONCOR.NS" },
  { name: "Gujarat Gas", ticker: "GUJGASLTD.NS" },
  { name: "Petronet LNG", ticker: "PETRONET.NS" },
  { name: "GAIL India", ticker: "GAIL.NS" },
  { name: "IOC (Indian Oil)", ticker: "IOC.NS" },
  { name: "HPCL", ticker: "HINDPETRO.NS" },
  { name: "Oil India", ticker: "OIL.NS" },
  { name: "Canara Bank", ticker: "CANBK.NS" },
  { name: "Bank of Baroda", ticker: "BANKBARODA.NS" },
  { name: "Punjab National Bank", ticker: "PNB.NS" },
  { name: "Union Bank of India", ticker: "UNIONBANK.NS" },
  { name: "Indian Bank", ticker: "INDIANB.NS" },
  { name: "Central Bank of India", ticker: "CENTRALBK.NS" },
  { name: "Yes Bank", ticker: "YESBANK.NS" },
  { name: "Max Healthcare", ticker: "MAXHEALTH.NS" },
  { name: "Fortis Healthcare", ticker: "FORTIS.NS" },
  { name: "Narayana Hrudayalaya", ticker: "NH.NS" },
  { name: "Metropolis Healthcare", ticker: "METROPOLIS.NS" },
  { name: "Dr Lal PathLabs", ticker: "LALPATHLAB.NS" },
  { name: "Thyrocare Technologies", ticker: "THYROCARE.NS" },
  { name: "Syngene International", ticker: "SYNGENE.NS" },
  { name: "Gland Pharma", ticker: "GLAND.NS" },
  { name: "Alkem Laboratories", ticker: "ALKEM.NS" },
  { name: "Ipca Laboratories", ticker: "IPCALAB.NS" },
  { name: "Laurus Labs", ticker: "LAURUSLABS.NS" },
  { name: "Natco Pharma", ticker: "NATCOPHARM.NS" },
  { name: "Zydus Lifesciences", ticker: "ZYDUSLIFE.NS" },
  { name: "Glenmark Pharma", ticker: "GLENMARK.NS" },
  { name: "Piramal Enterprises", ticker: "PEL.NS" },
  { name: "PI Industries", ticker: "PIIND.NS" },
  { name: "UPL Limited", ticker: "UPL.NS" },
  { name: "Coromandel International", ticker: "COROMANDEL.NS" },
  { name: "Deepak Nitrite", ticker: "DEEPAKNTR.NS" },
  { name: "SRF Limited", ticker: "SRF.NS" },
  { name: "Aarti Industries", ticker: "AARTIIND.NS" },
  { name: "Navin Fluorine", ticker: "NAVINFLUOR.NS" },
  { name: "Atul Limited", ticker: "ATUL.NS" },
  { name: "Clean Science", ticker: "CLEAN.NS" },
  { name: "Fine Organic Industries", ticker: "FINEORG.NS" },
  { name: "Alkyl Amines", ticker: "ALKYLAMINE.NS" },
  { name: "Balaji Amines", ticker: "BALAMINES.NS" },
  { name: "Vinati Organics", ticker: "VINATIORGA.NS" },
  { name: "Affle India", ticker: "AFFLE.NS" },
  { name: "Nazara Technologies", ticker: "NAZARA.NS" },
  { name: "Route Mobile", ticker: "ROUTE.NS" },
  { name: "Tanla Platforms", ticker: "TANLA.NS" },
  { name: "RateGain Travel", ticker: "RATEGAIN.NS" },
  { name: "Easy Trip Planners", ticker: "EASEMYTRIP.NS" },
  { name: "Sapphire Foods", ticker: "SAPPHIRE.NS" },
  { name: "Devyani International", ticker: "DEVYANI.NS" },
  { name: "Westlife Foodworld", ticker: "WESTLIFE.NS" },
  { name: "Restaurant Brands Asia", ticker: "RBA.NS" },
  { name: "Metro Brands", ticker: "METROBRAND.NS" },
  { name: "Campus Activewear", ticker: "CAMPUS.NS" },
  { name: "Aditya Birla Fashion", ticker: "ABFRL.NS" },
  { name: "V-Mart Retail", ticker: "VMART.NS" },
  { name: "Shoppers Stop", ticker: "SHOPERSTOP.NS" },
  { name: "Bata India", ticker: "BATAINDIA.NS" },
  { name: "Relaxo Footwears", ticker: "RELAXO.NS" }
];

/**
 * Search stocks by ticker or company name
 * @param {string} query - Search query
 * @param {number} limit - Maximum results to return
 * @returns {Array} Matching stocks
 */
export function searchStocks(query, limit = 10) {
  if (!query || query.trim() === '') {
    return [];
  }
  
  const searchTerm = query.toLowerCase().trim();
  
  const results = indianStocks.filter(stock => {
    const tickerMatch = stock.ticker.toLowerCase().includes(searchTerm);
    const nameMatch = stock.name.toLowerCase().includes(searchTerm);
    return tickerMatch || nameMatch;
  });
  
  // Sort: exact ticker matches first, then by name
  results.sort((a, b) => {
    const aTickerExact = a.ticker.toLowerCase().startsWith(searchTerm);
    const bTickerExact = b.ticker.toLowerCase().startsWith(searchTerm);
    if (aTickerExact && !bTickerExact) return -1;
    if (!aTickerExact && bTickerExact) return 1;
    return a.name.localeCompare(b.name);
  });
  
  return results.slice(0, limit);
}

export default indianStocks;
